apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "webhook.domain.local"
webhooks:
  - name: "webhook.domain.local"
    rules:
      - apiGroups: ["*"]
        apiVersions: ["*"]
        operations: ["*"]
        resources: ["*/*"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: "casbin-webhook-svc"
        path: /
        port: 8080
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZrQ0ZDeFJtd1VjeW1jT3Y3VUdtdUtyNFFEb3BiUWFNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1FVXgKQ3pBSkJnTlZCQVlUQWtGVk1STXdFUVlEVlFRSURBcFRiMjFsTFZOMFlYUmxNU0V3SHdZRFZRUUtEQmhKYm5SbApjbTVsZENCWGFXUm5hWFJ6SUZCMGVTQk1kR1F3SGhjTk1qSXdOekk0TURjd056STJXaGNOTXpJd056STFNRGN3Ck56STJXakJGTVFzd0NRWURWUVFHRXdKQlZURVRNQkVHQTFVRUNBd0tVMjl0WlMxVGRHRjBaVEVoTUI4R0ExVUUKQ2d3WVNXNTBaWEp1WlhRZ1YybGtaMmwwY3lCUWRIa2dUSFJrTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBcEJVazBwa2t5SHJ6aVNCZVRYb3ZuakcvSkJkS2tCSkcwRnB1b0NpT3Q3blZPTFdlCjFhY2pPaitmaXRLb001RjVBaVdKSnMzZUZ3NHg1WHhBL1k2Z0dTMEY4REd2K3cxbXNpSU5JR0pQcTNuNEo4SkcKNmtEendtWHNyd0VxNDVLMnJndVp2WGVuelpyNFFvV3ErUW1FY0tMTXVQZk5YZ2N5bEZUWEtVMVNmT3FqdGlaZwpWR1VyeGFGVXpDck1ZODJ1ZGI4aTZIZ0F4NjRrSEpyUk5XNXZHUG05cFd5UGxnMHZiWkZiRXpaeXhNYU5IWlBMCmowU1lBYTRTWlA0em1MTFVSSjQrSDlwalducWxheE8vaExFZW1ndE16Y2Fmd0pDT2lFSHFWNWIvRnFCYlpKQ1IKN2lqK3VZZ016T1FFc1dmakJBWWxya0lnaHB5aXdRV3M4blllYXdJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFBNEVIMlpFeDBTR1lxeUhnTWI5eU1IVXo3LzBLUXg4WDBZblU4cE1HSmJYeVlWYXZTMnBrZHBoclJYCnZNeWVTTGdJd2h1dEhEbFB0SDhlSUMwSmFmNFBRdUV6QnorMTRIRHVDcHNaVUw1TW4rak80WFVyTGM1SGlOQkcKa3Q2ODY3bzh2azJ6dWdOVldtN3VrMVJRd3ZRK2NKa3ZFQ0RXOTNuY0JPU1pNWnJ0MHdITGtWdG9nWUg2NitWawpxRTUwenFKS0JKUlZNZElOcEl4YTRiS3MwUVo3bG9KR2dpcFJsTDh2UHV6K2dIa3M3OFhmRmZtbGcwb3ZTZWlNCnQ4UG1SaEhIcDduc1E2YnVPa01McGZUNzY0ZjdNdjN3ellUWTNFRkxudkNtU2t0RUdvbVZCZ0RnUTdkdldDMWwKaWp4aTFhOFMzQUJaZmhjeWQyRzlVN21neWI0awotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
